# ConfiguraÃ§Ã£o bÃ¡sica do Jekyll
title: "Programa de Metas 2025-2028"
description: "Site oficial do Programa de Metas 2025-2028 da Prefeitura de SÃ£o Paulo"

# DefiniÃ§Ã£o do caminho base do site
baseurl: "/site_pdm_25_28_versao_inicial" # ğŸ”¹ Nome do repositÃ³rio
url: "https://h-pgy.github.io" # ğŸ”¹ URL base do GitHub Pages

# ConfiguraÃ§Ã£o do Sass (Garante que o Jekyll compila corretamente)
sass:
  sass_dir: _sass
  style: compressed  # Comprime o CSS para melhorar a performance


