# Configura√ß√£o b√°sica do Jekyll
title: "Programa de Metas 2025-2028"
description: "Site oficial do Programa de Metas 2025-2028 da Prefeitura de S√£o Paulo"

# Defini√ß√£o do caminho base do site
baseurl: "" # Nome do reposit√≥rio
url: "https://h-pgy.github.io/site_pdm_25_28_versao_inicial" # üîπ URL base do GitHub Pages

# Configura√ß√£o do Sass (Garante que o Jekyll compila corretamente)
sass:
  sass_dir: _sass
  style: compressed  # Comprime o CSS para melhorar a performance


